### ISSUE TITLE
Running nox creates a `poetry.lock` file

### ISSUE THREAD

**Issue by jugmac00** [eumiro/pygohome#9]
... which is not ignored in `.gitignore` which means after a nox run there are uncommitted changes.

I am not familiar with `poetry`, so am not sure what to do about this.

**Comment by eumiro** [comment]
That's correct, I forgot to add `poetry.lock`. Thank you.

Fixed in https://github.com/eumiro/pygohome/commit/e55096776288d13beb2d6747790ad90c69a8af80
